language: cpp
env:
    - STATSD_COMPILE_MODE=Debug
    # - STATSD_COMPILE_MODE=Release
branches:
  only: 
    - master
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
#      - valgrind
      - cppcheck
      - build-essential
before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        choco install visualstudio2019buildtools --package-parameters "--includeRecommended --includeOptional"
        choco install make cmake cppcheck tree visualstudio2017-workload-vctools mingw
        ;;
      linux)
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 50
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 50
        ;;
    esac
matrix:
  include:
    - os: linux
      dist: trusty
      script: make test STATSD_COMPILE_MODE=$STATSD_COMPILE_MODE
      after_script: make lint
    - os: osx
      osx_image: xcode10
      script: make test STATSD_COMPILE_MODE=$STATSD_COMPILE_MODE
      after_script: make lint
    - os: windows
      compiler: msvc19
      script: 
        - mkdir build && cd build
        - cmake -DCMAKE_BUILD_TYPE=$STATSD_COMPILE_MODE  ..
        - cmake --build .
        - tree
        - ./bin/$STATSD_COMPILE_MODE/statsd-test.exe
  allow_failures:
        - os: windows
